-- ER_Model - Data Modeling (Clinic_ER_Model)

-- DOCTOR Table

CREATE TABLE DOCTOR (
    DOCTOR_KEY VARCHAR2(5) PRIMARY KEY,
    DOCTOR_NAME VARCHAR2(50),
    CITY VARCHAR2(50),
    PHONE_NUMBER VARCHAR2(15),
    GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')),
    EXPERIENCE_YEAR NUMBER(2),
    EXPERTISE VARCHAR2(50)
);

CREATE INDEX IDX_DOCTOR_CITY ON DOCTOR(CITY);


-- PATIENT Table

CREATE TABLE PATIENT (
    PATIENT_KEY VARCHAR2(5) PRIMARY KEY,
    PATIENT_NAME VARCHAR2(50),
    PHONE_NUMBER VARCHAR2(15),
    GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')),
    TREATMENT VARCHAR2(50),
    ADDRESS VARCHAR2(100),
    AGE NUMBER(3)
);

CREATE INDEX IDX_PATIENT_TREATMENT ON PATIENT(TREATMENT);

-- TIME_TABLE Table

CREATE TABLE TIME_TABLE (
    TIME_KEY VARCHAR2(5) PRIMARY KEY,
    DAY VARCHAR2(2), 
    MONTH VARCHAR2(10), 
    QUARTER VARCHAR2(2),
    YEAR VARCHAR2(4)
);

CREATE INDEX IDX_TIME_MONTH ON TIME_TABLE(MONTH);

-- CLINIC Table

CREATE TABLE CLINIC (
    DOCTOR_KEY VARCHAR2(5),
    PATIENT_KEY VARCHAR2(5),
    TIME_KEY VARCHAR2(5),
    CHARGE NUMBER(6),
    COUNT NUMBER(6),
    CONSTRAINT D_K_FK FOREIGN KEY (DOCTOR_KEY) REFERENCES DOCTOR(DOCTOR_KEY),
    CONSTRAINT P_FK FOREIGN KEY (PATIENT_KEY) REFERENCES PATIENT(PATIENT_KEY),
    CONSTRAINT T_FK FOREIGN KEY (TIME_KEY) REFERENCES TIME_TABLE(TIME_KEY)
);

CREATE INDEX IDX_CLINIC_DOCTOR ON CLINIC(DOCTOR_KEY);
CREATE INDEX IDX_CLINIC_PATIENT ON CLINIC(PATIENT_KEY);
CREATE INDEX IDX_CLINIC_TIME ON CLINIC(TIME_KEY);


-- Select Statement Query With Joins (Example)

SELECT DOCTOR_NAME,EXPERTISE,CITY
  FROM DOCTOR D
  JOIN CLINIC C
  ON D.DOCTOR_KEY=C.DOCTOR_KEY
  JOIN PETIENT P
  ON P.PETIENT_KEY=C.PETIENT_KEY
  JOIN TIME T
  ON T.TIME_KEY=C.TIME_KEY
  WHERE ROWNUM<=5
  ORDER BY YEAR DESC;


SELECT * FROM
   CLINIC C
   JOIN DOCTOR D
   ON D.DOCTOR_KEY=C.DOCTOR_KEY
   JOIN PETIENT P
   ON P.PETIENT_KEY=C.PETIENT_KEY
   JOIN TIME T
   ON T.TIME_KEY=C.TIME_KEY
   WHERE ROWNUM<=5
   ORDER BY YEAR DESC;